In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
import pandas as pd
#1
df=pd.read_csv("/content/drive/MyDrive/DataSet/student.csv")
print("Top 5 rows")
print(df.head(5))
#2
print("Bottom 5 rows")
print(df.tail(5))
#3
print("Info about the datas")
print(df.info())
#4
print("Describing the datas")
print(df.describe())
#5
Label_column='Writing'
X=df.drop(columns=[Label_column])
Y=df[Label_column]


print('\nFeatures(X)')
print(X.head())

print("\nLabels (Y)")
print(Y.head())


Top 5 rows
   Math  Reading  Writing
0    48       68       63
1    62       81       72
2    79       80       78
3    76       83       79
4    59       64       62
Bottom 5 rows
     Math  Reading  Writing
995    72       74       70
996    73       86       90
997    89       87       94
998    83       82       78
999    66       66       72
Info about the datas
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Math     1000 non-null   int64
 1   Reading  1000 non-null   int64
 2   Writing  1000 non-null   int64
dtypes: int64(3)
memory usage: 23.6 KB
None
Describing the datas
              Math      Reading      Writing
count  1000.000000  1000.000000  1000.000000
mean     67.290000    69.872000    68.616000
std      15.085008    14.657027    15.241287
min      13.000000    19.000000    14.000000
25%      58.000000    60.750000    58.000000
50%      6

In [ ]:
import numpy as np

#dimension, d-features,n-samples
d,n=3,5
#Matrices:W-weights,X-features,Y-outputs
W=np.random.rand(d,1) #creates a random weight vector W of size d*1

X=np.random.rand(d,n)#Creates a random feature matrix X of size d*n
Y=W.T@X #computesY=W^TX,W^T tanspose of W
print("W:\n",W)
print("\nX:\n",X)
print("\nY:\n",Y)

W:
 [[0.52938704]
 [0.50971553]
 [0.41225222]]

X:
 [[0.94858236 0.05717661 0.787408   0.31622988 0.37131619]
 [0.9210293  0.34066979 0.03700109 0.53533377 0.43127261]
 [0.30384348 0.63840786 0.51310205 0.02499171 0.6784577 ]]

Y:
 [[1.0968903  0.4670983  0.64723108 0.45057883 0.69609202]]


In [5]:
##3
import pandas as pd
df=pd.DataFrame({
    'features1':range(1,11),
    'features2':range(11,21),
    'label':range(21,31)
})

df=df = df.sample(frac=1, random_state=42).reset_index(drop=True)

# 80-20 split
train_data = df[:int(0.8 * len(df))]
test_data = df[int(0.8 * len(df)):]

print("Training Data:")
print(train_data)

print("\nTesting Data:")
print(test_data)

Training Data:
   features1  features2  label
0          9         19     29
1          2         12     22
2          6         16     26
3          1         11     21
4          8         18     28
5          3         13     23
6         10         20     30
7          5         15     25

Testing Data:
   features1  features2  label
8          4         14     24
9          7         17     27


In [6]:
import numpy as np

# Define the cost function
def cost_function(X, Y, W):

    # Number of data points
    n = len(Y)

    # Hypothesis: y_pred = X.dot(W)
    y_pred = np.dot(X, W)

    # Calculate Mean Squared Error (MSE)
    cost = (1 / (2 * n)) * np.sum((y_pred - Y) ** 2)

    return cost

# Test Case
X_test = np.array([[1, 2], [3, 4], [5, 6]])
Y_test = np.array([3, 7, 11])
W_test = np.array([1, 1])

# Calculate cost
cost = cost_function(X_test, Y_test, W_test)

# Validate the result
if cost == 0:
    print("Proceed Further")
else:
    print("Something went wrong: Reimplement the cost function")
print("Cost function output:", cost)


Proceed Further
Cost function output: 0.0


In [9]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

# Gradient Descent Implementation
def gradient_descent(X, Y, W, alpha, iterations):
    n = len(Y)
    cost_history = []

    for i in range(iterations):
        # Predicted values
        Y_pred = np.dot(X, W)

        # Gradient calculation
        gradient = (1 / n) * np.dot(X.T, (Y_pred - Y))

        # Update weights
        W -= alpha * gradient

        # Calculate cos)t
        cost = (1 / (2 * n)) * np.sum((Y_pred - Y) ** 2)
        cost_history.append(cost)

    return W, cost_history

# RMSE
def rmse(Y_true, Y_pred):
    return np.sqrt(mean_squared_error(Y_true, Y_pred))


def main():
    #1
    data = pd.read_csv('/content/drive/MyDrive/DataSet/student.csv')

    #2
    X = data[['Math', 'Reading']].values
    Y = data['Writing'].values

    #3
    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

    #4
    X_train_mean = np.mean(X_train, axis=0)
    X_train_std = np.std(X_train, axis=0)
    X_train = (X_train - X_train_mean) / X_train_std
    X_test = (X_test - X_train_mean) / X_train_std


    X_train = np.c_[np.ones(X_train.shape[0]), X_train]
    X_test = np.c_[np.ones(X_test.shape[0]), X_test]

    #5
    W = np.zeros(X_train.shape[1])
    alpha = 0.01
    iterations = 1000

    #6
    W_optimal, cost_history = gradient_descent(X_train, Y_train, W, alpha, iterations)

    #7
    Y_pred = np.dot(X_test, W_optimal)

    #8
    model_rmse = rmse(Y_test, Y_pred)
    model_r2 = r2_score(Y_test, Y_pred)

    #results
    print("Final Weights:", W_optimal)
    print("Cost History (First 10 iterations):", cost_history[:10])
    print("RMSE on Test Set:", model_rmse)
    print("R-Squared on Test Set:", model_r2)

    for alpha_exp in [0.001, 0.1, 0.5]:
        W = np.zeros(X_train.shape[1])
        W_optimal, _ = gradient_descent(X_train, Y_train, W, alpha_exp, iterations)
        Y_pred = np.dot(X_test, W_optimal)
        print(f"Learning Rate: {alpha_exp}, RMSE: {rmse(Y_test, Y_pred)}, R-Squared: {r2_score(Y_test, Y_pred)}")

if __name__ == "__main__":
    main()

#Performance Evaluation:

#If RMSE is low and R² is close to 1, the model's performance is acceptable.
#A high RMSE or low R² may indicate underfitting or overfitting.
#Effect of Learning Rate:

#High learning rate (e.g., 0.5): May result in oscillations or failure to converge.
#Low learning rate (e.g., 0.001): Slower convergence but more stable.
#Optimal range (e.g., 0.01 - 0.1): Balances convergence speed and stability.

Final Weights: [68.66953532  2.16347922 12.47419677]
Cost History (First 10 iterations): [2471.69875, 2421.3066682841163, 2371.9712240257663, 2323.6694550601733, 2276.37892526855, 2230.077711644174, 2184.7443917038104, 2140.3580312344934, 2096.8981723659404, 2054.344821959219]
RMSE on Test Set: 4.796799265066206
R-Squared on Test Set: 0.9080797530286899
Learning Rate: 0.001, RMSE: 26.143425598603404, R-Squared: -1.7304427770835078
Learning Rate: 0.1, RMSE: 4.788030543047314, R-Squared: 0.9084155129091689
Learning Rate: 0.5, RMSE: 4.788030543283847, R-Squared: 0.9084155129001201
